kind: pipeline
name: greeting_test12

steps:
- name: en
  image: alpine
  commands:
  - echo hello
  - echo world

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde

- name: build-push-docker
  image: plugins/docker
  settings:
    registry: i2thub.icesi.edu.co:5000
    repo: ${DRONE_REPO,,}
	tags:
	- ${DRONE_SOURCE_BRANCH/\//-}
	- ${DRONE_SOURCE_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
