kind: pipeline
name: clone-build-push-release

steps:
- name: test
  image: alpine
  commands:
  - pwd
  - ls -l /var/run/
  - apk add docker
  - docker ps
  - docker images
  
- name: docker-test
  image: plugins/docker
  commands:
  - docker images
  - docker ps
  
- name: build-push-docker
  image: plugins/docker
  commands:
  - docker images
  - docker ps
  settings:
    #registry: i2thub.icesi.edu.co:5000
    context: ./flaskBaseImage
    dockerfile: ./flaskBaseImage/Dockerfile
    repo: yorjaggy/flaskpostgress_2
    username: yorjaggy
    password: holamundo1
    tags:
    - ${DRONE_COMMIT_BRANCH/\//-}
    - ${DRONE_COMMIT_BRANCH/\//-}-${DRONE_COMMIT_SHA:0:8}
    
  #- name: execute-webhook-portainer
  #  image: alpine
    #commands: #ubicar esta url como secret?
    #- apk add curl
    #- curl -X POST https://i2thub.icesi.edu.co:5443/api/webhooks/a5b9d67f-204d-47de-9cfb-729871ff524d
    #- curl -X POST https://i2thub.icesi.edu.co:5443/portainer/api/webhooks/a5b9d67f-204d-47de-9cfb-729871ff524d
