version: '3'
services:
  flask:
    image: poc_python_flask
    ports:
      - "5000:5000"
    depends_on:
      - db_pg
  
  db_pg:
    image: postgres
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: testdb
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 4343:8080

  
