version: '2'
services:
  flask:
    image: flaskmachine:latest
    ports:
      - "5000:5000"
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgresmachine:latest
    ports:
      - "5432:5432"

  
